apiVersion: 1
datasources:
  - name: InfluxDB-BMonitor
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: bmonitor
      defaultBucket: sensor_data
    secureJsonData:
      token: bmonitor-influx-dev-token-2026
    isDefault: true
    editable: true